import type { ActionContext } from "../../types";

interface Input {
  summary: string;
  highlights: string[];
  blockers: string[];
  nextUp?: string[];
  since?: string;
  org?: string;
  [key: string]: unknown;
}

export default {
  async execute(input: Input, ctx: ActionContext) {
    const { summary, highlights, blockers, nextUp, since, ...upstream } = input;
    const shell = ctx.capabilities.shell;

    // Build Discord message
    const lines: string[] = [];
    const today = new Date().toLocaleDateString("en-CH", { weekday: "long", year: "numeric", month: "long", day: "numeric" });

    lines.push(`**Metafactory Ecosystem Digest** — ${today}`);
    lines.push("");
    lines.push(summary);
    lines.push("");

    if (highlights.length > 0) {
      lines.push("**Highlights**");
      for (const h of highlights) {
        lines.push(`> ${h}`);
      }
      lines.push("");
    }

    if (blockers.length > 0) {
      lines.push("**Needs attention**");
      for (const b of blockers) {
        lines.push(`> ⚠️ ${b}`);
      }
      lines.push("");
    }

    if (nextUp && nextUp.length > 0) {
      lines.push("**Next up**");
      for (const n of nextUp) {
        lines.push(`> → ${n}`);
      }
      lines.push("");
    }

    lines.push("_Generated by Pulse P_ECOSYSTEM_DIGEST_");

    const digest = lines.join("\n");

    // Post to Discord if shell is available
    let posted = false;
    if (shell) {
      try {
        const escaped = digest.replace(/"/g, '\\"');
        const result = await shell(`bun ~/bin/discord post --channel general "${escaped}"`);
        posted = result.code === 0;
      } catch {
        // Discord posting is optional — don't fail the pipeline
        posted = false;
      }
    }

    return {
      ...upstream,
      summary,
      highlights,
      blockers,
      nextUp,
      digest,
      posted,
      formattedAt: new Date().toISOString(),
    };
  },
};
