import type { ActionContext } from "../../types";

interface ScoredItem {
  type: string;
  repo: string;
  id: string;
  title: string;
  labels: string[];
  url?: string;
  score: number;
  scoreBreakdown: string;
  description?: string;
}

interface Input {
  topPick: ScoredItem;
  reasoning: string;
  suggestedFirstStep?: string;
  totalCandidates?: number;
  rankedItems?: ScoredItem[];
  [key: string]: unknown;
}

export default {
  async execute(input: Input, _ctx: ActionContext) {
    const { topPick, reasoning, suggestedFirstStep, totalCandidates, rankedItems, ...upstream } = input;

    const today = new Date().toLocaleDateString("en-CH", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const lines: string[] = [];

    lines.push("╔═══════════════════════════════════════════════════════════╗");
    lines.push("║  metafactory — Next Pick                                 ║");
    lines.push("╚═══════════════════════════════════════════════════════════╝");
    lines.push("");
    lines.push(`  ${today}`);
    lines.push(`  Scanned ${totalCandidates ?? "?"} work items across the ecosystem`);
    lines.push("");
    lines.push("  ─── TOP PICK ───────────────────────────────────────────");
    lines.push("");
    lines.push(`  📌 ${topPick.id}`);
    lines.push(`     ${topPick.title}`);
    lines.push("");
    lines.push(`  Type:   ${topPick.type}`);
    lines.push(`  Repo:   ${topPick.repo}`);
    lines.push(`  Score:  ${topPick.score} (${topPick.scoreBreakdown})`);
    if (topPick.labels.length) {
      lines.push(`  Labels: ${topPick.labels.join(", ")}`);
    }
    if (topPick.url) {
      lines.push(`  URL:    ${topPick.url}`);
    }
    if (topPick.description) {
      lines.push("");
      lines.push(`  ${topPick.description}`);
    }
    lines.push("");
    lines.push("  ─── WHY THIS? ──────────────────────────────────────────");
    lines.push("");
    // Wrap reasoning at ~70 chars
    for (const sentence of reasoning.split(". ")) {
      const trimmed = sentence.trim();
      if (trimmed) lines.push(`  ${trimmed}${trimmed.endsWith(".") ? "" : "."}`);
    }
    lines.push("");
    if (suggestedFirstStep) {
      lines.push("  ─── FIRST STEP ─────────────────────────────────────────");
      lines.push("");
      lines.push(`  → ${suggestedFirstStep}`);
      lines.push("");
    }

    // Show runners-up (top 5)
    if (rankedItems && rankedItems.length > 1) {
      lines.push("  ─── RUNNERS-UP ─────────────────────────────────────────");
      lines.push("");
      const runnersUp = rankedItems
        .filter((item) => item.id !== topPick.id)
        .slice(0, 5);
      for (const item of runnersUp) {
        lines.push(`  ${item.score.toString().padStart(3)} │ [${item.type}] ${item.id}: ${item.title}`);
      }
      lines.push("");
    }

    lines.push("  Generated by Pulse F_NEXT_PICK");
    lines.push("");

    const digest = lines.join("\n");

    return {
      ...upstream,
      topPick,
      reasoning,
      suggestedFirstStep,
      digest,
      formattedAt: new Date().toISOString(),
    };
  },
};
